version: '3.9'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: 'no' # prevent auto-restart
    remove: true
