name: Release
on:
  push:
    branches:
      - main
      - master
      - alpha
      - beta
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Lint Code"
        run: npm run lint

      - name: "Check Prettier"
        run: npm run format:check

      - name: "Run Tests"
        run: npm run test
